/**
 * @copyright 2023-2024 Chris Zuber <admin@kernvalley.us>
 * @see https://wicg.github.io/sanitizer-api/#default-configuration-dictionary
 */

export const EVENT_PREFIX =  'aegis:';
export const EVENT_PREFIX_LENGTH = EVENT_PREFIX.length;

export const eventAttrs = [
	EVENT_PREFIX + 'abort', EVENT_PREFIX + 'blur', EVENT_PREFIX + 'focus',
	EVENT_PREFIX + 'cancel', EVENT_PREFIX + 'auxclick', EVENT_PREFIX + 'beforeinput',
	EVENT_PREFIX + 'beforetoggle', EVENT_PREFIX + 'canplay', EVENT_PREFIX + 'canplaythrough',
	EVENT_PREFIX + 'change', EVENT_PREFIX + 'click', EVENT_PREFIX + 'close',
	EVENT_PREFIX + 'contextmenu', EVENT_PREFIX + 'copy',  EVENT_PREFIX + 'cuechange',
	EVENT_PREFIX + 'cut', EVENT_PREFIX + 'dblclick', EVENT_PREFIX + 'drag',
	EVENT_PREFIX + 'dragend', EVENT_PREFIX + 'dragenter', EVENT_PREFIX + 'dragexit',
	EVENT_PREFIX + 'dragleave', EVENT_PREFIX + 'dragover', EVENT_PREFIX + 'dragstart',
	EVENT_PREFIX + 'drop', EVENT_PREFIX + 'durationchange', EVENT_PREFIX + 'emptied',
	EVENT_PREFIX + 'ended', EVENT_PREFIX + 'formdata', EVENT_PREFIX + 'input',
	EVENT_PREFIX + 'invalid', EVENT_PREFIX + 'keydown', EVENT_PREFIX + 'keypress',
	EVENT_PREFIX + 'keyup', EVENT_PREFIX + 'load', EVENT_PREFIX + 'loadeddata',
	EVENT_PREFIX + 'loadedmetadata', EVENT_PREFIX + 'loadstart', EVENT_PREFIX + 'mousedown',
	EVENT_PREFIX + 'mouseenter', EVENT_PREFIX + 'mouseleave', EVENT_PREFIX + 'mousemove',
	EVENT_PREFIX + 'mouseout', EVENT_PREFIX + 'mouseover', EVENT_PREFIX + 'mouseup',
	EVENT_PREFIX + 'wheel', EVENT_PREFIX + 'paste', EVENT_PREFIX + 'pause',
	EVENT_PREFIX + 'play', EVENT_PREFIX + 'playing', EVENT_PREFIX + 'progress',
	EVENT_PREFIX + 'ratechange', EVENT_PREFIX + 'reset', EVENT_PREFIX + 'resize',
	EVENT_PREFIX + 'scroll', EVENT_PREFIX + 'scrollend', EVENT_PREFIX + 'securitypolicyviolation',
	EVENT_PREFIX + 'seeked', EVENT_PREFIX + 'seeking', EVENT_PREFIX + 'select',
	EVENT_PREFIX + 'slotchange', EVENT_PREFIX + 'stalled', EVENT_PREFIX + 'submit',
	EVENT_PREFIX + 'suspend', EVENT_PREFIX + 'timeupdate', EVENT_PREFIX + 'volumechange',
	EVENT_PREFIX + 'waiting', EVENT_PREFIX + 'selectstart', EVENT_PREFIX + 'selectionchange',
	EVENT_PREFIX + 'toggle', EVENT_PREFIX + 'pointercancel', EVENT_PREFIX + 'pointerdown',
	EVENT_PREFIX + 'pointerup',  EVENT_PREFIX + 'pointermove', EVENT_PREFIX + 'pointerout',
	EVENT_PREFIX + 'pointerover', EVENT_PREFIX + 'pointerenter', EVENT_PREFIX + 'pointerleave',
	EVENT_PREFIX + 'gotpointercapture', EVENT_PREFIX + 'lostpointercapture',
	EVENT_PREFIX + 'mozfullscreenchange', EVENT_PREFIX + 'mozfullscreenerror',
	EVENT_PREFIX + 'animationcancel', EVENT_PREFIX + 'animationend', EVENT_PREFIX + 'animationiteration',
	EVENT_PREFIX + 'animationstart', EVENT_PREFIX + 'transitioncancel',
	EVENT_PREFIX + 'transitionend', EVENT_PREFIX + 'transitionrun', EVENT_PREFIX + 'transitionstart',
	EVENT_PREFIX + 'webkitanimationend', EVENT_PREFIX + 'webkitanimationiteration',
	EVENT_PREFIX + 'webkitanimationstart', EVENT_PREFIX + 'webkittransitionend',
	EVENT_PREFIX + 'error',
];

export const allowCustomElements = true;
export const allowUnknownMarkup = false;
export const allowComments = false;
export const allowElements = [
	'a', 'abbr', 'acronym', 'address', 'area', 'article', 'aside', 'audio', 'b',
	'bdi', 'bdo', 'bgsound', 'big', 'blockquote', 'body', 'br', 'button', 'canvas',
	'caption', 'center', 'cite', 'code', 'col', 'colgroup', 'datalist', 'dd',
	'del', 'details', 'dfn', 'dialog', 'dir', 'div', 'dl', 'dt', 'em', 'fieldset',
	'figcaption', 'figure', 'font', 'footer', 'form', 'h1', 'h2', 'h3', 'h4', 'h5',
	'h6', 'head', 'header', 'hgroup', 'hr', 'html', 'i', 'img', 'input', 'ins',
	'kbd', 'keygen', 'label', 'layer', 'legend', 'li', 'link', 'listing', 'main',
	'map', 'mark', 'marquee', 'menu', 'meta', 'meter', 'nav', 'nobr', 'ol',
	'optgroup', 'option', 'output', 'p', 'picture', 'popup', 'pre', 'progress',
	'q', 'rb', 'rp', 'rt', 'rtc', 'ruby', 's', 'samp', 'section', 'select',
	'selectmenu', 'slot', 'small', 'source', 'span', 'strike', 'strong',
	'style', 'sub', 'summary', 'sup', 'table', 'tbody', 'td', 'tfoot', 'th',
	'thead', 'time', 'tr', 'track', 'tt', 'u', 'ul', 'var', 'video', 'wbr',
];

export const allowAttributes = {
	'abbr': ['*'],
	'accept': ['*'],
	'accept-charset': ['*'],
	'accesskey': ['*'],
	'action': ['*'],
	'align': ['*'],
	'alink': ['*'],
	'allow': ['*'],
	'allowfullscreen': ['*'],
	'alt': ['*'],
	'anchor': ['*'],
	'archive': ['*'],
	'as': ['*'],
	'async': ['*'],
	'autocapitalize': ['*'],
	'autocomplete': ['*'],
	'autocorrect': ['*'],
	'autofocus': ['*'],
	'autopictureinpicture': ['*'],
	'autoplay': ['*'],
	'axis': ['*'],
	'background': ['*'],
	'behavior': ['*'],
	'bgcolor': ['*'],
	'border': ['*'],
	'bordercolor': ['*'],
	'capture': ['*'],
	'cellpadding': ['*'],
	'cellspacing': ['*'],
	'challenge': ['*'],
	'char': ['*'],
	'charoff': ['*'],
	'charset': ['*'],
	'checked': ['*'],
	'cite': ['*'],
	'class': ['*'],
	'classid': ['*'],
	'clear': ['*'],
	'code': ['*'],
	'codebase': ['*'],
	'codetype': ['*'],
	'color': ['*'],
	'cols': ['*'],
	'colspan': ['*'],
	'compact': ['*'],
	'content': ['*'],
	'contenteditable': ['*'],
	'controls': ['*'],
	'controlslist': ['*'],
	'conversiondestination': ['*'],
	'coords': ['*'],
	'crossorigin': ['*'],
	'csp': ['*'],
	'data': ['*'],
	'datetime': ['*'],
	'declare': ['*'],
	'decoding': ['*'],
	'default': ['*'],
	'defer': ['*'],
	'dir': ['*'],
	'direction': ['*'],
	'dirname': ['*'],
	'disabled': ['*'],
	'disablepictureinpicture': ['*'],
	'disableremoteplayback': ['*'],
	'disallowdocumentaccess': ['*'],
	'download': ['*'],
	'draggable': ['*'],
	'elementtiming': ['*'],
	'enctype': ['*'],
	'end': ['*'],
	'enterkeyhint': ['*'],
	'event': ['*'],
	'exportparts': ['*'],
	'face': ['*'],
	'for': ['*'],
	'form': ['*'],
	'formaction': ['*'],
	'formenctype': ['*'],
	'formmethod': ['*'],
	'formnovalidate': ['*'],
	'formtarget': ['*'],
	'frame': ['*'],
	'frameborder': ['*'],
	'headers': ['*'],
	'height': ['*'],
	'hidden': ['*'],
	'high': ['*'],
	'href': ['*'],
	'hreflang': ['*'],
	'hreftranslate': ['*'],
	'hspace': ['*'],
	'http-equiv': ['*'],
	'id': ['*'],
	'imagesizes': ['*'],
	'imagesrcset': ['*'],
	'importance': ['*'],
	'impressiondata': ['*'],
	'impressionexpiry': ['*'],
	'incremental': ['*'],
	'inert': ['*'],
	'inputmode': ['*'],
	'integrity': ['*'],
	'invisible': ['*'],
	'is': ['*'],
	'ismap': ['*'],
	'keytype': ['*'],
	'kind': ['*'],
	'label': ['*'],
	'lang': ['*'],
	'language': ['*'],
	'latencyhint': ['*'],
	'leftmargin': ['*'],
	'link': ['*'],
	'list': ['*'],
	'loading': ['*'],
	'longdesc': ['*'],
	'loop': ['*'],
	'low': ['*'],
	'lowsrc': ['*'],
	'manifest': ['*'],
	'marginheight': ['*'],
	'marginwidth': ['*'],
	'max': ['*'],
	'maxlength': ['*'],
	'mayscript': ['*'],
	'media': ['*'],
	'method': ['*'],
	'min': ['*'],
	'minlength': ['*'],
	'multiple': ['*'],
	'muted': ['*'],
	'name': ['*'],
	'nohref': ['*'],
	'nomodule': ['*'],
	'nonce': ['*'],
	'noresize': ['*'],
	'noshade': ['*'],
	'novalidate': ['*'],
	'nowrap': ['*'],
	'object': ['*'],
	'open': ['*'],
	'optimum': ['*'],
	'part': ['*'],
	'pattern': ['*'],
	'ping': ['*'],
	'placeholder': ['*'],
	'playsinline': ['*'],
	'policy': ['*'],
	'poster': ['*'],
	'preload': ['*'],
	'pseudo': ['*'],
	'readonly': ['*'],
	'referrerpolicy': ['*'],
	'rel': ['*'],
	'reportingorigin': ['*'],
	'required': ['*'],
	'resources': ['*'],
	'rev': ['*'],
	'reversed': ['*'],
	'role': ['*'],
	'rows': ['*'],
	'rowspan': ['*'],
	'rules': ['*'],
	'sandbox': ['*'],
	'scheme': ['*'],
	'scope': ['*'],
	'scopes': ['*'],
	'scrollamount': ['*'],
	'scrolldelay': ['*'],
	'scrolling': ['*'],
	'select': ['*'],
	'selected': ['*'],
	'shadowrootmode': ['*'],
	'shadowrootdelegatesfocus': ['*'],
	'shape': ['*'],
	'size': ['*'],
	'sizes': ['*'],
	'slot': ['*'],
	'span': ['*'],
	'spellcheck': ['*'],
	'src': ['*'],
	'srcdoc': ['*'],
	'srclang': ['*'],
	'srcset': ['*'],
	'standby': ['*'],
	'start': ['*'],
	'step': ['*'],
	'style': ['*'],
	'summary': ['*'],
	'tabindex': ['*'],
	'target': ['*'],
	'text': ['*'],
	'title': ['*'],
	'topmargin': ['*'],
	'translate': ['*'],
	'truespeed': ['*'],
	'trusttoken': ['*'],
	'type': ['*'],
	'usemap': ['*'],
	'valign': ['*'],
	'value': ['*'],
	'valuetype': ['*'],
	'version': ['*'],
	'virtualkeyboardpolicy': ['*'],
	'vlink': ['*'],
	'vspace': ['*'],
	'webkitdirectory': ['*'],
	'width': ['*'],
	'wrap': ['*'],
	'aegis:event:capture': ['*'],
	'aegis:event:passive': ['*'],
	'aegis:event:once': ['*'],
	...Object.fromEntries(eventAttrs.map(attr => [attr, ['*']]))
};

export const sanitizerConfig = {
	allowCustomElements, allowUnknownMarkup, allowComments, allowElements,
	allowAttributes,
};
